[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
remappings = [
  "forge-std/=lib/forge-std/src/",
  "account-abstraction/=lib/account-abstraction/contracts/",
  "aave-address-book/=lib/aave-address-book/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "aave-v3-origin/=lib/aave-address-book/lib/aave-v3-origin/src/",
  "solidity-utils/=lib/aave-address-book/lib/aave-v3-origin/lib/solidity-utils/src/",
]
